// Guest reviews for The Hart House, sourced from the live Airbnb listing.
// https://www.airbnb.ca/rooms/1631598477076471125
// Snapshot taken 21 September 2026: 4.9 average across 30 reviews (29 five-star).

export type GuestReview = {
  id: string;
  name: string;
  subtitle: string;
  rating: number;
  date: string;
  quote: string;
  photo?: string;
};

/** Listing-level stats, mirrored from the Airbnb listing. */
export const LISTING_STATS = {
  rating: 4.9,
  totalReviews: 30,
  fiveStarReviews: 29,
  listingUrl: "https://www.airbnb.ca/rooms/1631598477076471125",
} as const;

/**
 * Per-category scores as Airbnb reports them. Raw values are stored unrounded and
 * formatted to one decimal at render, which is how Airbnb displays them
 * (e.g. 4.97 shows as 5.0).
 */
export const CATEGORY_RATINGS = [
  { label: "Cleanliness", value: 4.9 },
  { label: "Accuracy", value: 4.87 },
  { label: "Check-in", value: 4.97 },
  { label: "Communication", value: 4.97 },
  { label: "Location", value: 4.83 },
  { label: "Value", value: 4.83 },
] as const;

export const GUEST_REVIEWS: GuestReview[] = [
  {
    id: "1769735563989110720",
    name: "Andrew",
    subtitle: "Salem, Oregon",
    rating: 5,
    date: "September 2026",
    quote: "Perfect place, and loved the location. It was extraordinarily clean and fit us very well. It was in a quiet location and it was very comfortable. No problems at all! A plus for everything!",
    photo: "/reviews/andrew.jpg",
  },
  {
    id: "1763934109019582722",
    name: "Leo",
    subtitle: "1 month on Airbnb",
    rating: 5,
    date: "August 2026",
    quote: "sam was very communicative and kind, host addressed problems without us having to bring up any concerns of our own. very nice and cozy space to stay in surrey!",
  },
  {
    id: "1763107800076238140",
    name: "Arkhy",
    subtitle: "Calgary, Canada",
    rating: 5,
    date: "August 2026",
    quote: "The place was clean and cozy. We were provided with all the things we needed to feel at home.",
    photo: "/reviews/arkhy.jpg",
  },
  {
    id: "1758771054355532312",
    name: "Rd",
    subtitle: "Saskatoon, Canada",
    rating: 5,
    date: "August 2026",
    quote: "A good size unit with nicely organized furniture. A great place to stay in Surrey especially if you’re with family. Communication with Sam was easy and he responded quickly with all our queries.",
    photo: "/reviews/rd.jpg",
  },
  {
    id: "1756701966823269969",
    name: "Himanshu",
    subtitle: "Victoria, Canada",
    rating: 5,
    date: "August 2026",
    quote: "Good place to stay",
    photo: "/reviews/himanshu.jpg",
  },
  {
    id: "1754414555414464456",
    name: "Asha",
    subtitle: "4 months on Airbnb",
    rating: 5,
    date: "August 2026",
    quote: "Sam is a welcoming host and I would stay at his basement suite again, and highly recommend it to others.",
    photo: "/reviews/asha.jpg",
  },
  {
    id: "1751571639518189090",
    name: "Daniel D.",
    subtitle: "2 months on Airbnb",
    rating: 5,
    date: "August 2026",
    quote: "Very nice place, Very good host, Answers fast aswell",
    photo: "/reviews/daniel-d.jpg",
  },
  {
    id: "1750790928179746017",
    name: "Daniel D.",
    subtitle: "2 months on Airbnb",
    rating: 5,
    date: "August 2026",
    quote: "Great host great place !",
    photo: "/reviews/daniel-d.jpg",
  },
  {
    id: "1750135365444356706",
    name: "Daniel D.",
    subtitle: "2 months on Airbnb",
    rating: 5,
    date: "August 2026",
    quote: "Very good host, very nice & clean place",
    photo: "/reviews/daniel-d.jpg",
  },
  {
    id: "1749355741018883286",
    name: "Braydon",
    subtitle: "White Rock, Canada",
    rating: 5,
    date: "August 2026",
    quote: "Had a wonderful little get away with my partner here, really cozy and comfortable, whole place was as described and very well will be coming back to your amazing home Sam 10/10",
    photo: "/reviews/braydon.jpg",
  },
  {
    id: "1748728704881564842",
    name: "Harsh",
    subtitle: "Burlington, Canada",
    rating: 5,
    date: "August 2026",
    quote: "Sam is an amazing host and was always quick to respond and accommodating. The Airbnb was very clean and perfect for our group. I would highly recommend!",
    photo: "/reviews/harsh.jpg",
  },
  {
    id: "1744312721601191423",
    name: "Bhupinder",
    subtitle: "1 month on Airbnb",
    rating: 5,
    date: "August 2026",
    quote: "This was only my 2nd Air B&B stay on my first ever trip using Air B&B back to back so I'm still getting used to navigating the app and how everything works. Even though there were clear instructions I was still hesitant with my approach to everything since this was a very new experience to me. I noticed I asked several questions which might have been obvious given the description of the Air B&B but I wanted to reconfirm regardless. Through it all, Sam was very patient with me and answered all my inquiries. He was very kind and consistent with checking up with how I was doing and my stay at the residence. I really appreciated this because it gave me more confidence to ask for clarification when I needed one. He was so calm and kind abojt everything and just took the pressure off of being a guest. I would definitely book this spot again with my family like I did this time. Very organized, clean, kind and many amenities. I truly appreciate him letting us stay. Thank you again !",
    photo: "/reviews/bhupinder.jpg",
  },
  {
    id: "1743608833747901053",
    name: "Brea",
    subtitle: "Tampa, Florida",
    rating: 5,
    date: "August 2026",
    quote: "We had a great stay here in Surrey! This Airbnb was perfect for a little stay and was very clean and accessible!",
    photo: "/reviews/brea.jpg",
  },
  {
    id: "1735570833536235868",
    name: "Bo",
    subtitle: "10 months on Airbnb",
    rating: 5,
    date: "July 2026",
    quote: "Great place!",
    photo: "/reviews/bo.jpg",
  },
  {
    id: "1734157261031742537",
    name: "Abdulmajid",
    subtitle: "Edmonton, Canada",
    rating: 5,
    date: "July 2026",
    quote: "Sam’s place was perfect for a quick weekend stay in the Lower Mainland. Comfortable, spacious, clean, beautiful neighborhood- everything you’re looking for in a stay.",
    photo: "/reviews/abdulmajid.jpg",
  },
  {
    id: "1732764135086345983",
    name: "Bob",
    subtitle: "Edmonton, Canada",
    rating: 5,
    date: "July 2026",
    quote: "My family enjoyed our stay at Sam's Airbnb in Surrey. Very nice and comfortable place. Sam responded quickly to any questions. We would definitely stay again if we visit Surrey. Thanks",
    photo: "/reviews/bob.jpg",
  },
  {
    id: "1729791295497252533",
    name: "Tahira",
    subtitle: "Calgary, Canada",
    rating: 5,
    date: "July 2026",
    quote: "Sam was super responsive and neat clean place \nWe will definitely visit again",
    photo: "/reviews/tahira.jpg",
  },
  {
    id: "1728405473146183389",
    name: "Narinder",
    subtitle: "8 months on Airbnb",
    rating: 5,
    date: "July 2026",
    quote: "Overall good experience:)",
    photo: "/reviews/narinder.jpg",
  },
  {
    id: "1721240863380670796",
    name: "Hira",
    subtitle: "Edmonton, Canada",
    rating: 5,
    date: "July 2026",
    quote: "Very good and nice place",
    photo: "/reviews/hira.jpg",
  },
  {
    id: "1718258195255757479",
    name: "Patrick",
    subtitle: "Calgary, Canada",
    rating: 5,
    date: "June 2026",
    quote: "Great stay",
    photo: "/reviews/patrick.jpg",
  },
  {
    id: "1717600525173234041",
    name: "Nabil",
    subtitle: "Surrey, Canada",
    rating: 5,
    date: "June 2026",
    quote: "Great place to stay, Sam is friendly and accommodating and was proactive in offering assistance since we were moving. The place is pristine clean, cozy and the bed in the living room is comfortable to sleep on. There’s a portable heater if it gets cold at nights during summer. The master bedroom is nicely tucked away and extremely cozy. The mattress is fabulous! \nThank you Sam for having us!",
    photo: "/reviews/nabil.jpg",
  },
  {
    id: "1716252745214099671",
    name: "Harmeen",
    subtitle: "5 months on Airbnb",
    rating: 5,
    date: "June 2026",
    quote: "Felt like home, would definitely like to come back. Clean and spacious and beautifully decorated.",
    photo: "/reviews/harmeen.jpg",
  },
  {
    id: "1714778897252660014",
    name: "Satyen",
    subtitle: "11 years on Airbnb",
    rating: 5,
    date: "June 2026",
    quote: "Sam's apartment is nice and comfortable. He is a great communicator and made sure that our stay was pleasant. The apartment is well appointed and carefully and caringly furnished. We had everything we needed and more. The neighborhood is nice. We would love to stay there again. Thank you, Sam!",
    photo: "/reviews/satyen.jpg",
  },
  {
    id: "1712436997728873237",
    name: "Ibrahim",
    subtitle: "Edmonton, Canada",
    rating: 5,
    date: "June 2026",
    quote: "Great host, very accommodating, place was very spacious and clean",
    photo: "/reviews/ibrahim.jpg",
  },
  {
    id: "1708188013041061887",
    name: "Iryna",
    subtitle: "Winnipeg, Canada",
    rating: 5,
    date: "June 2026",
    quote: "We had a wonderful stay! The place was clean, comfortable, and exactly as described. The host was friendly, responsive, and made the check-in process very easy. We would definitely stay here again and highly recommend it to others.",
    photo: "/reviews/iryna.jpg",
  },
  {
    id: "1707531292798208518",
    name: "Brian",
    subtitle: "2 years on Airbnb",
    rating: 5,
    date: "June 2026",
    quote: "Although we only stayed one night, making it a quick visit, this stay stood out as fantastic. Super clean, well stocked, matched the description, and literally nothing to disappoint at all. This is why we stay in airbnb’s. Thanks again Sam. Hope we stay with you again in the future.",
    photo: "/reviews/brian.jpg",
  },
  {
    id: "1706021437821736849",
    name: "Elijah",
    subtitle: "3 years on Airbnb",
    rating: 5,
    date: "June 2026",
    quote: "Exactly like the pictures! Super spacious inside and easy to find!",
    photo: "/reviews/elijah.jpg",
  },
  {
    id: "1704570470624325807",
    name: "J",
    subtitle: "3 months on Airbnb",
    rating: 5,
    date: "June 2026",
    quote: "10/10 🔥 🔥 🔥",
    photo: "/reviews/j.jpg",
  },
  {
    id: "1703721842665988975",
    name: "Michelle",
    subtitle: "Edmonton, Canada",
    rating: 5,
    date: "June 2026",
    quote: "Clean and comfy stay!",
    photo: "/reviews/michelle.jpg",
  },
];
